---
- name: Create CA directory 
  become: true
  file: path="{{ca_config_path}}" state=directory
- name: Create Cert directory 
  become: true
  file: path="{{cert_config_path}}" state=directory
- name: Create Key directory 
  become: true
  file: path="{{key_config_path}}" state=directory
- name: Create serial file
  become: true
  copy:
    src: ./files/serial
    dest: "{{ca_config_path}}/serial"
- name: Create certindex
  become: true
  file:
    path: "{{ca_config_path}}/certindex"
    state: touch
- name: Create openssl conf 
  become: true
  template:
    src: files/ca.j2
    dest: "{{ca_config_path}}/ca.conf"
- name: Create generate_key.sh 
  become: true
  template:
    src: files/generate_keys.sh.j2
    dest: "{{ca_config_path}}/generate_keys.sh"